title: James Ringsby # your name (or website title) here
logo: "/images/Ringsby_Jimmy_Headshot.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Mechanical Enginneer @ Cornell University | 2023
  <br><br>
  Hello! I'm a mechanical engineering student interested in product design and development, sustainability, aerospace, and more.  
  <br><br>
  <a href="https://www.linkedin.com/in/jamesringsby/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
